name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: windows-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '4.7.2' # Wählen Sie die passende .NET-Version

    - name: Restore NuGet Packages
      run: nuget restore FlickrClient.sln

    - name: Build
      run: msbuild /p:Configuration=Release FlickrClient.sln
