name: .NET Build

on: [push, pull_request]

jobs:
  test:
    runs-on: windows-latest
   
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Restore NuGet Packages
      run: nuget restore FlickrClient.sln

    - name: Build Solution (.NET Framework)
      run: msbuild FlickrClient.sln /p:Configuration=Release 
      
# Uncomment these lines if you want to run tests
#    - name: Run tests (NET Framework)
#      run: vstest.console.exe YourTestProject.dll
